"""Cadastros (categorias lojas, canais, vendedores, empresas, usuários, campos customizados, contratos, notificações, homologação) endpoints for the Bling v3 API."""

from .spec import Endpoint, Param

ENDPOINTS = (
    # --- categorias lojas --------------------------------------------------
    Endpoint(
        name="list_categorias_lojas",
        method="GET",
        path="categorias/lojas",
        description="List store categories linked to product categories.",
        query_params=(
            Param("pagina", int),
            Param("limite", int),
            Param("idLoja", int),
            Param("idCategoriaProduto", int),
            Param("idCategoriaProdutoPai", int),
        ),
    ),
    Endpoint(
        name="get_categoria_loja",
        method="GET",
        path="categorias/lojas/{idCategoriaLoja}",
        description="Get a store category by id.",
        path_params=(Param("idCategoriaLoja", int),),
    ),
    Endpoint(
        name="create_categoria_loja",
        method="POST",
        path="categorias/lojas",
        description="Link a store category to a product category.",
        has_body=True,
    ),
    Endpoint(
        name="update_categoria_loja",
        method="PUT",
        path="categorias/lojas/{idCategoriaLoja}",
        description="Replace a store category link.",
        path_params=(Param("idCategoriaLoja", int),),
        has_body=True,
    ),
    Endpoint(
        name="delete_categoria_loja",
        method="DELETE",
        path="categorias/lojas/{idCategoriaLoja}",
        description="Remove a store category link.",
        path_params=(Param("idCategoriaLoja", int),),
    ),
    # --- canais de venda -----------------------------------------------------
    Endpoint(
        name="list_canais_venda",
        method="GET",
        path="canais-venda",
        description="List sales channels.",
        query_params=(
            Param("pagina", int),
            Param("limite", int),
            Param("tipos", list),
            Param("situacao", int),
            Param("agrupador", int),
        ),
    ),
    Endpoint(
        name="get_canal_venda",
        method="GET",
        path="canais-venda/{idCanalVenda}",
        description="Get a sales channel by id.",
        path_params=(Param("idCanalVenda", int),),
    ),
    Endpoint(
        name="get_canal_venda_types",
        method="GET",
        path="canais-venda/tipos",
        description="List sales channel types.",
        query_params=(Param("agrupador", int),),
    ),
    # --- vendedores ------------------------------------------------------------
    Endpoint(
        name="list_vendedores",
        method="GET",
        path="vendedores",
        description="List salespeople (GET /vendedores).",
        query_params=(
            Param("pagina", int),
            Param("limite", int),
            Param("nomeContato", str),
            Param("situacaoContato", str),
            Param("idContato", int),
            Param("idLoja", int),
            Param("dataAlteracaoInicial", str),
            Param("dataAlteracaoFinal", str),
        ),
    ),
    Endpoint(
        name="get_vendedor",
        method="GET",
        path="vendedores/{idVendedor}",
        description="Get a salesperson by id.",
        path_params=(Param("idVendedor", int),),
    ),
    # --- empresas ----------------------------------------------------------------
    Endpoint(
        name="get_empresa_me",
        method="GET",
        path="empresas/me/dados-basicos",
        description="Get the current company's basic data.",
    ),
    # --- usuarios ------------------------------------------------------------------
    Endpoint(
        name="validate_hash",
        method="GET",
        path="usuarios/verificar-hash",
        description="Validate a user hash.",
        query_params=(Param("hash", str),),
    ),
    Endpoint(
        name="change_password",
        method="PATCH",
        path="usuarios/redefinir-senha",
        description="Reset the current user's password.",
        has_body=True,
    ),
    Endpoint(
        name="recover_password",
        method="POST",
        path="usuarios/recuperar-senha",
        description="Send a password recovery request by e-mail.",
        has_body=True,
    ),
    # --- campos customizados ------------------------------------------------------
    Endpoint(
        name="delete_campo_customizado",
        method="DELETE",
        path="campos-customizados/{idCampoCustomizado}",
        description="Delete a custom field.",
        path_params=(Param("idCampoCustomizado", int),),
    ),
    Endpoint(
        name="get_campos_customizados_modules",
        method="GET",
        path="campos-customizados/modulos",
        description="List modules that have custom fields.",
    ),
    Endpoint(
        name="get_campos_customizados_types",
        method="GET",
        path="campos-customizados/tipos",
        description="List custom field types.",
    ),
    Endpoint(
        name="find_campos_customizados_by_module",
        method="GET",
        path="campos-customizados/modulos/{idModulo}",
        description="List custom fields for a module.",
        path_params=(Param("idModulo", int),),
        query_params=(Param("pagina", int), Param("limite", int)),
    ),
    Endpoint(
        name="get_campo_customizado",
        method="GET",
        path="campos-customizados/{idCampoCustomizado}",
        description="Get a custom field by id.",
        path_params=(Param("idCampoCustomizado", int),),
    ),
    Endpoint(
        name="change_situation_campo_customizado",
        method="PATCH",
        path="campos-customizados/{idCampoCustomizado}/situacoes",
        description="Change a custom field's status.",
        path_params=(Param("idCampoCustomizado", int),),
        has_body=True,
    ),
    Endpoint(
        name="create_campo_customizado",
        method="POST",
        path="campos-customizados",
        description="Create a custom field.",
        has_body=True,
    ),
    Endpoint(
        name="update_campo_customizado",
        method="PATCH",
        path="campos-customizados/{idCampoCustomizado}",
        description="Update a custom field.",
        path_params=(Param("idCampoCustomizado", int),),
        has_body=True,
    ),
    # --- contratos -----------------------------------------------------------------
    Endpoint(
        name="delete_contrato",
        method="DELETE",
        path="contratos/{idContrato}",
        description="Delete a contract.",
        path_params=(Param("idContrato", int),),
    ),
    Endpoint(
        name="list_contratos",
        method="GET",
        path="contratos",
        description="List contracts.",
        query_params=(
            Param("pagina", int),
            Param("limite", int),
            Param("dataCriacaoInicio", str),
            Param("dataCriacaoFinal", str),
            Param("dataBaseInicio", str),
            Param("dataBaseFinal", str),
            Param("situacao", int),
            Param("idContato", int),
            Param("idContatoCobranca", int),
        ),
    ),
    Endpoint(
        name="get_contrato",
        method="GET",
        path="contratos/{idContrato}",
        description="Get a contract by id.",
        path_params=(Param("idContrato", int),),
    ),
    Endpoint(
        name="create_contrato",
        method="POST",
        path="contratos",
        description="Create a contract.",
        has_body=True,
    ),
    Endpoint(
        name="update_contrato",
        method="PUT",
        path="contratos/{idContrato}",
        description="Replace a contract.",
        path_params=(Param("idContrato", int),),
        has_body=True,
    ),
    # --- notificacoes --------------------------------------------------------------
    Endpoint(
        name="list_notificacoes",
        method="GET",
        path="notificacoes",
        description="List a company's notifications for a period.",
        query_params=(Param("periodo", str),),
    ),
    Endpoint(
        name="mark_notificacao_read",
        method="POST",
        path="notificacoes/{idNotificacao}/confirmar-leitura",
        description="Mark a notification as read.",
        path_params=(Param("idNotificacao", str),),
        has_body=True,
    ),
    # --- homologacao ---------------------------------------------------------------
    Endpoint(
        name="delete_homologacao",
        method="DELETE",
        path="homologacao/produtos/{idProdutoHomologacao}",
        description="Remove the homologation product.",
        path_params=(Param("idProdutoHomologacao", int),),
    ),
    Endpoint(
        name="get_homologacao",
        method="GET",
        path="homologacao/produtos",
        description="Get the homologation product.",
    ),
    Endpoint(
        name="change_situation_homologacao",
        method="PATCH",
        path="homologacao/produtos/{idProdutoHomologacao}",
        description="Change the homologation product's status.",
        path_params=(Param("idProdutoHomologacao", int),),
        has_body=True,
    ),
    Endpoint(
        name="create_homologacao",
        method="POST",
        path="homologacao/produtos",
        description="Create the homologation product.",
        has_body=True,
    ),
    Endpoint(
        name="update_homologacao",
        method="PUT",
        path="homologacao/produtos/{idProdutoHomologacao}",
        description="Replace the homologation product.",
        path_params=(Param("idProdutoHomologacao", int),),
        has_body=True,
    ),
)
