"""Financeiro endpoints for the Bling v3 API."""

from .spec import Endpoint, Param

ENDPOINTS = (
    # --- contas a pagar ------------------------------------------------------
    Endpoint(
        name="list_contas_pagar",
        method="GET",
        path="contas/pagar",
        description="List accounts payable.",
        query_params=(
            Param("pagina", int),
            Param("limite", int),
            Param("dataEmissaoInicial", str),
            Param("dataEmissaoFinal", str),
            Param("dataVencimentoInicial", str),
            Param("dataVencimentoFinal", str),
            Param("dataPagamentoInicial", str),
            Param("dataPagamentoFinal", str),
            Param("situacao", str),
            Param("idContato", int),
        ),
    ),
    Endpoint(
        name="get_conta_pagar",
        method="GET",
        path="contas/pagar/{idContaPagar}",
        description="Get an account payable by id.",
        path_params=(Param("idContaPagar", int),),
    ),
    Endpoint(
        name="create_conta_pagar",
        method="POST",
        path="contas/pagar",
        description="Create an account payable.",
        has_body=True,
    ),
    Endpoint(
        name="update_conta_pagar",
        method="PUT",
        path="contas/pagar/{idContaPagar}",
        description="Replace an account payable.",
        path_params=(Param("idContaPagar", int),),
        has_body=True,
    ),
    Endpoint(
        name="delete_conta_pagar",
        method="DELETE",
        path="contas/pagar/{idContaPagar}",
        description="Delete an account payable.",
        path_params=(Param("idContaPagar", int),),
    ),
    Endpoint(
        name="download_conta_pagar",
        method="POST",
        path="contas/pagar/{idContaPagar}/baixar",
        description="Settle (baixar) an account payable.",
        path_params=(Param("idContaPagar", int),),
        has_body=True,
    ),
    # --- contas a receber -----------------------------------------------------
    Endpoint(
        name="list_contas_receber",
        method="GET",
        path="contas/receber",
        description="List accounts receivable.",
        query_params=(
            Param("pagina", int),
            Param("limite", int),
            Param("situacoes", list),
            Param("tipoFiltroData", str),
            Param("dataInicial", str),
            Param("dataFinal", str),
            Param("idsCategorias", list),
            Param("idPortador", int),
            Param("idVendedor", int),
            Param("idFormaPagamento", int),
        ),
    ),
    Endpoint(
        name="get_conta_receber",
        method="GET",
        path="contas/receber/{idContaReceber}",
        description="Get an account receivable by id.",
        path_params=(Param("idContaReceber", int),),
    ),
    Endpoint(
        name="create_conta_receber",
        method="POST",
        path="contas/receber",
        description="Create an account receivable.",
        has_body=True,
    ),
    Endpoint(
        name="update_conta_receber",
        method="PUT",
        path="contas/receber/{idContaReceber}",
        description="Replace an account receivable.",
        path_params=(Param("idContaReceber", int),),
        has_body=True,
    ),
    Endpoint(
        name="delete_conta_receber",
        method="DELETE",
        path="contas/receber/{idContaReceber}",
        description="Delete an account receivable.",
        path_params=(Param("idContaReceber", int),),
    ),
    Endpoint(
        name="download_conta_receber",
        method="POST",
        path="contas/receber/{idContaReceber}/baixar",
        description="Settle (baixar) an account receivable.",
        path_params=(Param("idContaReceber", int),),
        has_body=True,
    ),
    Endpoint(
        name="get_bank_slips_conta_receber",
        method="GET",
        path="contas/receber/boletos",
        description="Get bank slips (boletos) for an account receivable origin.",
        query_params=(
            Param("idOrigem", int),
            Param("situacoes", list),
        ),
    ),
    Endpoint(
        name="cancel_bank_slips_conta_receber",
        method="POST",
        path="contas/receber/boletos/cancelar",
        description="Cancel bank slips (boletos) of an account receivable.",
        has_body=True,
    ),
    # --- formas de pagamento ---------------------------------------------------
    Endpoint(
        name="list_formas_pagamento",
        method="GET",
        path="formas-pagamentos",
        description="List payment methods.",
        query_params=(
            Param("pagina", int),
            Param("limite", int),
            Param("descricao", str),
            Param("tiposPagamentos", list),
            Param("situacao", str),
        ),
    ),
    Endpoint(
        name="get_forma_pagamento",
        method="GET",
        path="formas-pagamentos/{idFormaPagamento}",
        description="Get a payment method by id.",
        path_params=(Param("idFormaPagamento", int),),
    ),
    Endpoint(
        name="create_forma_pagamento",
        method="POST",
        path="formas-pagamentos",
        description="Create a payment method.",
        has_body=True,
    ),
    Endpoint(
        name="update_forma_pagamento",
        method="PUT",
        path="formas-pagamentos/{idFormaPagamento}",
        description="Replace a payment method.",
        path_params=(Param("idFormaPagamento", int),),
        has_body=True,
    ),
    Endpoint(
        name="delete_forma_pagamento",
        method="DELETE",
        path="formas-pagamentos/{idFormaPagamento}",
        description="Delete a payment method.",
        path_params=(Param("idFormaPagamento", int),),
    ),
    # --- contas contábeis --------------------------------------------------------
    Endpoint(
        name="list_contas_contabeis",
        method="GET",
        path="contas-contabeis",
        description="List accounting accounts.",
        query_params=(
            Param("pagina", int),
            Param("limite", int),
            Param("ocultarInvisiveis", str),
            Param("ocultarContasIntegracaoPagamento", str),
            Param("ocultarTipoContaBancaria", str),
            Param("situacoes", list),
        ),
    ),
    Endpoint(
        name="get_conta_contabil",
        method="GET",
        path="contas-contabeis/{idContaContabil}",
        description="Get an accounting account by id.",
        path_params=(Param("idContaContabil", int),),
    ),
    # --- categorias de receitas e despesas --------------------------------------
    Endpoint(
        name="list_categorias_receitas_despesas",
        method="GET",
        path="categorias/receitas-despesas",
        description="List revenue/expense categories.",
        query_params=(
            Param("pagina", int),
            Param("limite", int),
            Param("tipo", str),
            Param("situacao", str),
        ),
    ),
    Endpoint(
        name="get_categoria_receita_despesa",
        method="GET",
        path="categorias/receitas-despesas/{idCategoria}",
        description="Get a revenue/expense category by id.",
        path_params=(Param("idCategoria", int),),
    ),
    # --- borderôs ----------------------------------------------------------------
    Endpoint(
        name="get_bordero",
        method="GET",
        path="borderos/{idBordero}",
        description="Get a bordero (bank remittance batch) by id.",
        path_params=(Param("idBordero", int),),
    ),
    Endpoint(
        name="delete_bordero",
        method="DELETE",
        path="borderos/{idBordero}",
        description="Delete a bordero.",
        path_params=(Param("idBordero", int),),
    ),
)
