"""Produtos domain endpoints for the Bling v3 API.

Covers the SDK source modules: produtos, produtosEstruturas,
produtosFornecedores, produtosLojas, produtosVariacoes, gruposDeProdutos,
categoriasProdutos (see AlexandreBellas/bling-erp-api-js).
"""

from .spec import Endpoint, Param

ENDPOINTS = (
    # --- produtos ------------------------------------------------------------
    Endpoint(
        "list_produtos",
        "GET",
        "produtos",
        "List products",
        query_params=(
            Param("pagina", int),
            Param("limite", int),
            Param("criterio", str),
            Param("tipo", str),
            Param("idComponente", int),
            Param("dataInclusaoInicial", str),
            Param("dataInclusaoFinal", str),
            Param("dataAlteracaoInicial", str),
            Param("dataAlteracaoFinal", str),
            Param("idCategoria", int),
            Param("idLoja", int),
            Param("codigo", str),
            Param("nome", str),
            Param("idsProdutos", list),
            Param("codigos", list),
        ),
    ),
    Endpoint(
        "get_produto",
        "GET",
        "produtos/{idProduto}",
        "Get a product",
        path_params=(Param("idProduto", int),),
    ),
    Endpoint(
        "create_produto",
        "POST",
        "produtos",
        "Create a product",
        has_body=True,
    ),
    Endpoint(
        "update_produto",
        "PUT",
        "produtos/{idProduto}",
        "Replace a product",
        path_params=(Param("idProduto", int),),
        has_body=True,
    ),
    Endpoint(
        "delete_produto",
        "DELETE",
        "produtos/{idProduto}",
        "Delete a product",
        path_params=(Param("idProduto", int),),
    ),
    Endpoint(
        "delete_produtos",
        "DELETE",
        "produtos",
        "Delete multiple products",
        query_params=(Param("idsProdutos", list),),
    ),
    Endpoint(
        "change_situation_produto",
        "PATCH",
        "produtos/{idProduto}/situacoes",
        "Change a product situation",
        path_params=(Param("idProduto", int),),
        has_body=True,
    ),
    Endpoint(
        "change_situation_produtos",
        "POST",
        "produtos/situacoes",
        "Change multiple products situation",
        has_body=True,
    ),
    # --- produtos - estruturas -------------------------------------------------
    Endpoint(
        "get_produto_estrutura",
        "GET",
        "produtos/estruturas/{idProdutoEstrutura}",
        "Get the structure (bill of materials) of a composite product",
        path_params=(Param("idProdutoEstrutura", int),),
    ),
    Endpoint(
        "add_produto_estrutura_componente",
        "POST",
        "produtos/estruturas/{idProdutoEstrutura}/componentes",
        "Add component(s) to a product structure",
        path_params=(Param("idProdutoEstrutura", int),),
        has_body=True,
    ),
    Endpoint(
        "update_produto_estrutura",
        "PUT",
        "produtos/estruturas/{idProdutoEstrutura}",
        "Replace the structure of a composite product",
        path_params=(Param("idProdutoEstrutura", int),),
        has_body=True,
    ),
    Endpoint(
        "change_produto_estrutura_componente",
        "PATCH",
        "produtos/estruturas/{idProdutoEstrutura}/componentes/{idComponente}",
        "Change a component of a product structure",
        path_params=(
            Param("idProdutoEstrutura", int),
            Param("idComponente", int),
        ),
        has_body=True,
    ),
    Endpoint(
        "delete_produto_estrutura_componentes",
        "DELETE",
        "produtos/estruturas/{idProdutoEstrutura}/componentes",
        "Remove specific components from a product structure",
        path_params=(Param("idProdutoEstrutura", int),),
        query_params=(Param("idsComponentes", list),),
    ),
    Endpoint(
        "delete_produtos_estruturas",
        "DELETE",
        "produtos/estruturas",
        "Delete the structure of multiple products",
        query_params=(Param("idsProdutos", list),),
    ),
    # --- produtos - fornecedores -------------------------------------------------
    Endpoint(
        "list_produtos_fornecedores",
        "GET",
        "produtos/fornecedores",
        "List product-supplier links",
        query_params=(
            Param("pagina", int),
            Param("limite", int),
            Param("idProduto", int),
            Param("idFornecedor", int),
        ),
    ),
    Endpoint(
        "get_produto_fornecedor",
        "GET",
        "produtos/fornecedores/{idProdutoFornecedor}",
        "Get a product-supplier link",
        path_params=(Param("idProdutoFornecedor", int),),
    ),
    Endpoint(
        "create_produto_fornecedor",
        "POST",
        "produtos/fornecedores",
        "Create a product-supplier link",
        has_body=True,
    ),
    Endpoint(
        "update_produto_fornecedor",
        "PUT",
        "produtos/fornecedores/{idProdutoFornecedor}",
        "Replace a product-supplier link",
        path_params=(Param("idProdutoFornecedor", int),),
        has_body=True,
    ),
    Endpoint(
        "delete_produto_fornecedor",
        "DELETE",
        "produtos/fornecedores/{idProdutoFornecedor}",
        "Delete a product-supplier link",
        path_params=(Param("idProdutoFornecedor", int),),
    ),
    # --- produtos - lojas --------------------------------------------------------
    Endpoint(
        "list_produtos_lojas",
        "GET",
        "produtos/lojas",
        "List product-store links",
        query_params=(
            Param("pagina", int),
            Param("limite", int),
            Param("idProduto", int),
            Param("idLoja", int),
            Param("idCategoriaProduto", int),
        ),
    ),
    Endpoint(
        "get_produto_loja",
        "GET",
        "produtos/lojas/{idProdutoLoja}",
        "Get a product-store link",
        path_params=(Param("idProdutoLoja", int),),
    ),
    Endpoint(
        "create_produto_loja",
        "POST",
        "produtos/lojas",
        "Create a product-store link",
        has_body=True,
    ),
    Endpoint(
        "update_produto_loja",
        "PUT",
        "produtos/lojas/{idProdutoLoja}",
        "Replace a product-store link",
        path_params=(Param("idProdutoLoja", int),),
        has_body=True,
    ),
    Endpoint(
        "delete_produto_loja",
        "DELETE",
        "produtos/lojas/{idProdutoLoja}",
        "Delete a product-store link",
        path_params=(Param("idProdutoLoja", int),),
    ),
    # --- produtos - variações ------------------------------------------------
    Endpoint(
        "get_produto_variacoes",
        "GET",
        "produtos/variacoes/{idProdutoPai}",
        "Get a parent product with its variations",
        path_params=(Param("idProdutoPai", int),),
    ),
    Endpoint(
        "change_attribute_name_produto_variacoes",
        "PATCH",
        "produtos/variacoes/{idProdutoPai}/atributos",
        "Change the attribute name across a product's variations",
        path_params=(Param("idProdutoPai", int),),
        has_body=True,
    ),
    Endpoint(
        "generate_combinations_produto_variacoes",
        "POST",
        "produtos/variacoes/atributos/gerar-combinacoes",
        "Generate new variation combinations for a parent product",
        has_body=True,
    ),
    # --- grupos de produtos ------------------------------------------------------
    Endpoint(
        "list_grupos_produtos",
        "GET",
        "grupos-produtos",
        "List product groups",
        query_params=(
            Param("nome", str),
            Param("nomePai", str),
            Param("pagina", int),
            Param("limite", int),
        ),
    ),
    Endpoint(
        "get_grupo_produto",
        "GET",
        "grupos-produtos/{idGrupoProduto}",
        "Get a product group",
        path_params=(Param("idGrupoProduto", int),),
    ),
    Endpoint(
        "create_grupo_produto",
        "POST",
        "grupos-produtos",
        "Create a product group",
        has_body=True,
    ),
    Endpoint(
        "update_grupo_produto",
        "PUT",
        "grupos-produtos/{idGrupoProduto}",
        "Replace a product group",
        path_params=(Param("idGrupoProduto", int),),
        has_body=True,
    ),
    Endpoint(
        "delete_grupo_produto",
        "DELETE",
        "grupos-produtos/{idGrupoProduto}",
        "Delete a product group",
        path_params=(Param("idGrupoProduto", int),),
    ),
    Endpoint(
        "delete_grupos_produtos",
        "DELETE",
        "grupos-produtos",
        "Delete multiple product groups",
        query_params=(Param("idsGruposProdutos", list),),
    ),
    # --- categorias - produtos -----------------------------------------------
    Endpoint(
        "list_categorias_produtos",
        "GET",
        "categorias/produtos",
        "List product categories",
        query_params=(Param("pagina", int), Param("limite", int)),
    ),
    Endpoint(
        "get_categoria_produto",
        "GET",
        "categorias/produtos/{idCategoriaProduto}",
        "Get a product category",
        path_params=(Param("idCategoriaProduto", int),),
    ),
    Endpoint(
        "create_categoria_produto",
        "POST",
        "categorias/produtos",
        "Create a product category",
        has_body=True,
    ),
    Endpoint(
        "update_categoria_produto",
        "PUT",
        "categorias/produtos/{idCategoriaProduto}",
        "Replace a product category",
        path_params=(Param("idCategoriaProduto", int),),
        has_body=True,
    ),
    Endpoint(
        "delete_categoria_produto",
        "DELETE",
        "categorias/produtos/{idCategoriaProduto}",
        "Delete a product category",
        path_params=(Param("idCategoriaProduto", int),),
    ),
)
